### PR TITLE
Fix csv parsing issue

### LINKED ISSUE #20: Upload a csv file errors
Reported here: https://github.com/meilisearch/meilisearch/discussions/4958#discussioncomment-10754262

When uploading a csv file all of the fields are getting merged into a single field. So:

```csv
field 1, field1
```

becomes

```
field 1field2
```

### PR DESCRIPTION
**Pull request by sanders41**
# Pull Request

## Related issue
Fixes #20

## What does this PR do?
- Adds a `,` between items when parsing a csv file

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by sanders41** [comment]
@Kerollmops when I run on main now it never sends anything to Meilisearch for me. In main.rs it never enters the loop `for chunk in csv::CsvChunker::new(file, size, opt.csv_delimiter) {`

**Comment by Kerollmops** [comment]
Ok, I can reproduce, it seems related to the size of the CSV, fixing it. Thank you.

**Comment by sanders41** [comment]
The problem is: `if self.writer.get_ref().len() + self.record.len() >= self.size {` should be `if self.writer.get_ref().len() + self.record.len() <= self.size {`

**Comment by Kerollmops** [comment]
Yup, I fixed it on main by counting records now. Can you try?

**Comment by sanders41** [comment]
Tested and all good now :+1:

**Comment by Kerollmops** [comment]
Releasing a new new new version 😅

**Pull request closed without merging**
